"""adiciona ultimo snapshot meteorologico

Revision ID: 384b0121d9cc
Revises: d99b349de6bb
Create Date: 2026-09-09 08:47:37.222194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384b0121d9cc'
down_revision: Union[str, Sequence[str], None] = 'd99b349de6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('weather_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activities', sa.Column('weather_temperature', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('activities', sa.Column('weather_apparent_temperature', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('activities', sa.Column('weather_precipitation_probability', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('weather_precipitation', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('activities', sa.Column('weather_code', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('weather_wind_speed', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('activities', sa.Column('weather_wind_gusts', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('activities', sa.Column('weather_assessment_level', sa.String(length=20), nullable=True))
    op.add_column('activities', sa.Column('weather_assessment_reasons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'weather_assessment_reasons')
    op.drop_column('activities', 'weather_assessment_level')
    op.drop_column('activities', 'weather_wind_gusts')
    op.drop_column('activities', 'weather_wind_speed')
    op.drop_column('activities', 'weather_code')
    op.drop_column('activities', 'weather_precipitation')
    op.drop_column('activities', 'weather_precipitation_probability')
    op.drop_column('activities', 'weather_apparent_temperature')
    op.drop_column('activities', 'weather_temperature')
    op.drop_column('activities', 'weather_checked_at')
    # ### end Alembic commands ###
