"""cria tabela de atividades

Revision ID: d99b349de6bb
Revises: 
Create Date: 2026-09-03 09:58:15.921176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99b349de6bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PLANNED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_activity_type', 'activities', ['activity_type'], unique=False)
    op.create_index('ix_activities_scheduled_date', 'activities', ['scheduled_date'], unique=False)
    op.create_index('ix_activities_status', 'activities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_status', table_name='activities')
    op.drop_index('ix_activities_scheduled_date', table_name='activities')
    op.drop_index('ix_activities_activity_type', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
